type: object
additionalProperties: false
required: [bucket]
properties:

  bucket: {$ref: "#/definitions/bucket"}

  tags:
    description: >
      Optional tags attached to your stack to make it easier to track and monitor.
    type: object
