{{#each buckets}}
MixinMediaBucket{{resourceTitle}}:
  Type: "AWS::S3::Bucket"
  DeletionPolicy: Retain
  Properties:
    BucketName: {{name}}
    CorsConfiguration:
      CorsRules:
        - AllowedHeaders:
            - "*"
          AllowedMethods:
            - "GET"
            - "PUT"
          AllowedOrigins:
            - "*"
          ExposedHeaders:
            - Access-Control-Allow-Origin
            - Access-Control-Allow-Methods
            - Access-Control-Allow-Headers
            - ETag
          MaxAge: {{expires}}
    LifecycleConfiguration:
      Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 1
          Status: Enabled

# Allows anyone to *read* a given object, but prevents scanning of our media resources through list.
MixinMediaBucket{{resourceTitle}}Policy:
  Type: AWS::S3::BucketPolicy
  DeletionPolicy: Retain
  Properties:
    Bucket: {{name}}
    PolicyDocument:
      Statement:
        - Action:
            - "s3:GetObject"
          Effect: "Allow"
          Resource: "arn:aws:s3:::{{name}}/*"
          Principal: "*"
{{/each}}

{{#each edges}}
MixinMediaBucket{{resourceTitle}}CF:
  Type: "AWS::CloudFront::Distribution"
  Properties:
    DistributionConfig:
      Aliases:
        - {{hostname}}
      Comment: CloudFront Distribution of the Panda Sky Media Mixin
      DefaultCacheBehavior:
        AllowedMethods: ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
        CachedMethods: ["GET", "HEAD", "OPTIONS"]
        Compress: false
        DefaultTTL: {{expires}}
        ForwardedValues:
          Cookies:
            Forward: "all"
          Headers: ["Accept", "Accept-Charset", "Accept-Datetime", "Accept-Language", "Access-Control-Request-Headers", "Access-Control-Request-Method", "Authorization", "Origin", "Referer"]
          QueryString: true
          QueryStringCacheKeys: ["*"]
        MaxTTL: {{expires}}
        MinTTL: 0
        SmoothStreaming: false
        TargetOriginId: "MixinMediaBucket{{resourceTitle}}"
        ViewerProtocolPolicy: redirect-to-https
      DefaultRootObject: ""
      Enabled: true
      HttpVersion: http2
      IPV6Enabled: false
      Origins:
        - Id: "MixinMediaBucket{{resourceTitle}}"
          DomainName: {{bucketDomainName}}
          OriginPath: ""
          S3OriginConfig: {}
      PriceClass: {{priceClass}}
      ViewerCertificate:
        AcmCertificateArn: {{certificate}}
        MinimumProtocolVersion: "TLSv1.2_2018"
        SslSupportMethod: "sni-only"
    # Tags:
    # {{#each tags}}
    #   - Key: {{Key}}
    #     Value: {{Value}}
    # {{/each}}

MixinMediaBucket{{resourceTitle}}DNS:
  Type: AWS::Route53::RecordSetGroup
  DependsOn:
    - "MixinMediaBucket{{resourceTitle}}CF"
  Properties:
    Comment: Media endpoint
    HostedZoneName: {{hostedzone}}
    RecordSets:
      - Name: {{hostname}}
        Type: A
        AliasTarget:
          DNSName:
            "Fn::GetAtt":
              - "MixinMediaBucket{{resourceTitle}}CF"
              - "DomainName"
          EvaluateTargetHealth: false
          HostedZoneId: Z2FDTNDATAQYW2

{{/each}}
